### ISSUE TITLE
Bypassing disallow_x_transition and disallow_transition_from_x

### ISSUE THREAD

**Issue by tomrittervg** [struct/mapguard#1]
It looks like you can bypass disallow_x_transition by changing a page's permissions by going RW -> R -> RX. And disallow_transition_from_x by going RX -> R -> WR.

I think this can be easily prevented by changing the Map Cache Entry's prot field to not store the current protection; but rather any protection it has ever seen.

**Comment by struct** [comment]
Agree you can bypass it this way. I like your idea though. I just pushed a change that tracks historical protection bits and stores them immutably.
